# Configuração do Nixpacks para Langflow com dependências adicionais
# Compatível com EasyPanel versão 1.34.1

[build]
builder = "python"

[variables]
PYTHON_VERSION = "3.12"
NODE_VERSION = "20"

# Pacotes Nix - apenas pacotes válidos do Nix
[phases.setup]
nixPkgs = [
  "python312",
  "nodejs_20",
  "playwright",
  "chromium",
  "git",
  "curl",
  "wget",
  "gcc",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "python312Packages.wheel"
]

# Pacotes que serão instalados via apt-get
[phases.setup.aptPkgs]
cmds = [
  "apt-get update",
  "apt-get install -y build-essential libglib2.0-0 libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2 libatspi2.0-0 libxshmfence1"
]

[phases.install]
cmds = [
  "pip install -e . --extra postgresql",
  "pip install playwright==1.42.0 autogen-ai autogenstudio typing-extensions==4.9.0",
  "playwright install --with-deps chromium",
  "cd src/frontend && npm install"
]

[phases.build]
cmds = ["cd src/frontend && npm run build"]

[start]
cmd = "python -m src.backend.langflow run"